In [1]:
import pandas as pd
import json
import sqlite3

In [2]:
# reading the json and csv files
listings_df = pd.read_json("C:/Users/HP/Downloads/listings_final_expanded.json")

In [3]:
property_df = pd.read_json("C:/Users/HP/Downloads/property_attributes_final_expanded.json")

In [4]:
agents_df = pd.read_json("C:/Users/HP/Downloads/agents_cleaned.json")

In [5]:
sales_df = pd.read_csv("C:/Users/HP/Downloads/sales_cleaned.csv")

In [6]:
buyers_df = pd.read_json("C:/Users/HP/Downloads/buyers_cleaned.json")

In [7]:
listings_df.head()

#CHANGING THE FORMAT OF PRICE FROM SCIENTIFIC ANNOTATION TO INTEGER.  
listings_df["Price"] = listings_df["Price"].astype(int)

In [8]:
property_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [9]:
agents_df.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [10]:
sales_df.head()

#CHANGING THE FORMAT OF PRICE FROM SCIENTIFIC ANNOTATION TO INTEGER.  
sales_df["Sale_Price"] = sales_df["Sale_Price"].astype(int)

In [11]:
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [12]:
#checking wheather null value is there.
listings_df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [13]:
print(property_df.isnull().sum())

attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

In [14]:
print(agents_df.isnull().sum())

Agent_ID            0
Name                0
Phone               0
Email               0
commission_rate     0
deals_closed        0
rating              0
experience_years    0
avg_closing_days    0
dtype: int64

In [15]:
print(sales_df.isnull().sum())

Listing_ID        0
Sale_Price        0
Date_Sold         0
Days_on_Market    0
dtype: int64

In [16]:
print(buyers_df.isnull().sum())

buyer_id            0
sale_id             0
buyer_type          0
payment_mode        0
loan_taken          0
loan_provider    9966
loan_amount         0
dtype: int64

In [17]:
for col in buyers_df.columns:
    if buyers_df[col].dtype == "object":
        buyers_df[col].fillna("Unknown", inplace=True)
    else:
        buyers_df[col].fillna(buyers_df[col].median(), inplace=True)

In [18]:
print(buyers_df.isnull().sum())

buyer_id         0
sale_id          0
buyer_type       0
payment_mode     0
loan_taken       0
loan_provider    0
loan_amount      0
dtype: int64

In [19]:
conn = sqlite3.connect("realestate.db")   # creates database file
cursor = conn.cursor()

print("Connected to SQLite")

Connected to SQLite

In [20]:
listings_df.to_sql("listings", conn, if_exists="replace", index=False)

21200

In [21]:
listings_df = pd.read_sql("SELECT * FROM listings", conn)
print(listings_df.head())

  Listing_ID         City Property_Type    Price         Sqft Date_Listed  \
0     L00001     New York     Apartment  1655144  2753.009121  2023-05-06
1     L00002  Los Angeles     Apartment  1519141  4966.988193  2023-02-14
2     L00003      Houston     Apartment   162488  1267.003959  2023-04-22
3     L00004      Phoenix     Apartment  1277015  2128.014429  2024-01-02
4     L00005      Phoenix     Townhouse   562297  4178.997421  2023-10-29

  Agent_ID   Latitude   Longitude
0    A0015  33.965208  -69.861589
1    A0038  42.547892  -90.277860
2    A0015  28.732327 -115.952982
3    A0042  26.403938  -74.771490
4    A0018  39.425252  -83.917878

In [22]:
# Property table
property_df.to_sql("property", conn, if_exists="replace", index=False)

# Agents table
agents_df.to_sql("agents", conn, if_exists="replace", index=False)

# Sales table
sales_df.to_sql("sales", conn, if_exists="replace", index=False)

# Buyers table
buyers_df.to_sql("buyers", conn, if_exists="replace", index=False)

print("All tables created successfully!")

All tables created successfully!

In [23]:
property_df = pd.read_sql("SELECT * FROM property", conn)
print(property_df.head())

   attribute_id listing_id  bedrooms  bathrooms  floor_number  total_floors  \
0             1     L00001         5          3             9             9
1             2     L00002         2          2            19            29
2             3     L00003         2          3             8            26
3             4     L00004         3          3            25            10
4             5     L00005         2          2            15            16

   year_built  is_rented  tenant_count furnishing_status  metro_distance_km  \
0        2001          1             4         Furnished               7.26
1        2020          0             0       Unfurnished               4.84
2        2007          1             4    Semi-Furnished               4.92
3        2003          0             3         Furnished               1.20
4        2008          1             1    Semi-Furnished               7.90

   parking_available  power_backup
0                  0             1
1                  1             0
2                  0             0
3                  0             1
4                  0             0

In [24]:
property_df = pd.read_sql("SELECT * FROM property", conn)
print(property_df.head())

   attribute_id listing_id  bedrooms  bathrooms  floor_number  total_floors  \
0             1     L00001         5          3             9             9
1             2     L00002         2          2            19            29
2             3     L00003         2          3             8            26
3             4     L00004         3          3            25            10
4             5     L00005         2          2            15            16

   year_built  is_rented  tenant_count furnishing_status  metro_distance_km  \
0        2001          1             4         Furnished               7.26
1        2020          0             0       Unfurnished               4.84
2        2007          1             4    Semi-Furnished               4.92
3        2003          0             3         Furnished               1.20
4        2008          1             1    Semi-Furnished               7.90

   parking_available  power_backup
0                  0             1
1                  1             0
2                  0             0
3                  0             1
4                  0             0

In [25]:
agents_df = pd.read_sql("SELECT * FROM agents", conn)
print(agents_df.head())

  Agent_ID         Name            Phone                 Email  \
0    A0001  Agent A0001  +1-534-665-8373  a0001@realestate.com
1    A0002  Agent A0002  +1-493-463-4698  a0002@realestate.com
2    A0003  Agent A0003  +1-290-534-1121  a0003@realestate.com
3    A0004  Agent A0004  +1-691-610-4878  a0004@realestate.com
4    A0005  Agent A0005  +1-829-613-5411  a0005@realestate.com

   commission_rate  deals_closed  rating  experience_years  avg_closing_days
0             2.00            52     4.3                10                64
1             2.20            26     3.8                20                82
2             2.85           297     3.6                21                83
3             1.67            31     4.5                 5                61
4             1.11           198     4.3                16                67

In [26]:
sales_df = pd.read_sql("SELECT * FROM sales", conn)
print(sales_df.head())

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776585  2023-05-01      116.000152

In [27]:
buyers_df = pd.read_sql("SELECT * FROM buyers", conn)
print(buyers_df.head())

   buyer_id sale_id buyer_type   payment_mode  loan_taken loan_provider  \
0         1  L01179   End User           Cash           0       Unknown
1         2  L00866   Investor         Cheque           0       Unknown
2         3  L00102   Investor         Cheque           1          Axis
3         4  L00440   Investor  Bank Transfer           0       Unknown
4         5  L00059   Investor            UPI           1          HDFC

   loan_amount
0            0
1            0
2      2317757
3            0
4      4191221

In [28]:
from IPython.display import display

display("The Listing Data is:",listings_df.head())
display("The Property Data is:",property_df.head())
display("The Agents Data is:",agents_df.head())
display("The Sales Data is:",sales_df.head())
display("The Buyers Data is:",buyers_df.head())

'The Listing Data is:'

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162488,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277015,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878

'The Property Data is:'

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,1,4,Furnished,7.26,0,1
1,2,L00002,2,2,19,29,2020,0,0,Unfurnished,4.84,1,0
2,3,L00003,2,3,8,26,2007,1,4,Semi-Furnished,4.92,0,0
3,4,L00004,3,3,25,10,2003,0,3,Furnished,1.20,0,1
4,5,L00005,2,2,15,16,2008,1,1,Semi-Furnished,7.90,0,0

'The Agents Data is:'

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

'The Sales Data is:'

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776585  2023-05-01      116.000152

'The Buyers Data is:'

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,Unknown,0
1,2,L00866,Investor,Cheque,0,Unknown,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,Unknown,0
4,5,L00059,Investor,UPI,1,HDFC,4191221

In [29]:
create_table_listing = """ 
CREATE TABLE IF NOT EXISTS listings (
    Listing_ID TEXT PRIMARY KEY, 
    Address TEXT,
    City TEXT,
    State TEXT,
    Zip TEXT,
    Property_Type TEXT,
    Price REAL,
    Area_sqft REAL,
    Agent_ID TEXT, 
    Listed_Date TEXT, 
    FOREIGN KEY (Agent_ID) REFERENCES agents(Agent_ID)
);
""" 

cursor.execute(create_table_listing)
conn.commit()

print("Listings table created successfully!")

Listings table created successfully!

In [30]:
listings_df.to_sql("listings", conn, if_exists="append", index=False)

21200

In [31]:
cursor.execute("PRAGMA table_info(listings);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Listing_ID', 'TEXT', 0, None, 0)
(1, 'City', 'TEXT', 0, None, 0)
(2, 'Property_Type', 'TEXT', 0, None, 0)
(3, 'Price', 'INTEGER', 0, None, 0)
(4, 'Sqft', 'REAL', 0, None, 0)
(5, 'Date_Listed', 'TEXT', 0, None, 0)
(6, 'Agent_ID', 'TEXT', 0, None, 0)
(7, 'Latitude', 'REAL', 0, None, 0)
(8, 'Longitude', 'REAL', 0, None, 0)

In [32]:
create_property_attributes_table = """ 
CREATE TABLE IF NOT EXISTS property_attributes ( 
    attribute_id INTEGER PRIMARY KEY, 
    listing_id TEXT UNIQUE,
    bedrooms INTEGER,
    bathrooms INTEGER,
    floor_number INTEGER,
    total_floors INTEGER,
    year_built INTEGER,
    is_rented BOOLEAN, 
    tenant_count INTEGER,
    furnishing_status TEXT,
    metro_distance_km REAL,
    parking_available BOOLEAN,
    power_backup BOOLEAN, 
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""

cursor.execute(create_property_attributes_table) 
conn.commit()

print("Property table created successfully!")

Property table created successfully!

In [33]:
cursor.execute("PRAGMA table_info(property);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'attribute_id', 'INTEGER', 0, None, 0)
(1, 'listing_id', 'TEXT', 0, None, 0)
(2, 'bedrooms', 'INTEGER', 0, None, 0)
(3, 'bathrooms', 'INTEGER', 0, None, 0)
(4, 'floor_number', 'INTEGER', 0, None, 0)
(5, 'total_floors', 'INTEGER', 0, None, 0)
(6, 'year_built', 'INTEGER', 0, None, 0)
(7, 'is_rented', 'INTEGER', 0, None, 0)
(8, 'tenant_count', 'INTEGER', 0, None, 0)
(9, 'furnishing_status', 'TEXT', 0, None, 0)
(10, 'metro_distance_km', 'REAL', 0, None, 0)
(11, 'parking_available', 'INTEGER', 0, None, 0)
(12, 'power_backup', 'INTEGER', 0, None, 0)

In [34]:
create_agents_table = """
CREATE TABLE IF NOT EXISTS agents (
    agent_id INTEGER PRIMARY KEY, 
    name TEXT,
    phone INT,
    commission_rate REAL,
    deals_closed INTEGER,
    rating REAL,
    experience_years INTEGER,
    avg_closing_days INTEGER,
    FOREIGN KEY(agent_id) REFERENCES agents(agent_id)
);
"""

cursor.execute(create_agents_table)
conn.commit()

print("Agents table created successfully!")

Agents table created successfully!

In [35]:
cursor.execute("PRAGMA table_info(agents);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Agent_ID', 'TEXT', 0, None, 0)
(1, 'Name', 'TEXT', 0, None, 0)
(2, 'Phone', 'TEXT', 0, None, 0)
(3, 'Email', 'TEXT', 0, None, 0)
(4, 'commission_rate', 'REAL', 0, None, 0)
(5, 'deals_closed', 'INTEGER', 0, None, 0)
(6, 'rating', 'REAL', 0, None, 0)
(7, 'experience_years', 'INTEGER', 0, None, 0)
(8, 'avg_closing_days', 'INTEGER', 0, None, 0)

In [36]:
create_sales_table = """
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id TEXT,
    sale_price REAL,
    date_sold TEXT,
    days_on_market REAL,
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""

cursor.execute(create_sales_table)
conn.commit()

print("Sales table created successfully!")

Sales table created successfully!

In [37]:
cursor.execute("PRAGMA table_info(sales);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Listing_ID', 'TEXT', 0, None, 0)
(1, 'Sale_Price', 'INTEGER', 0, None, 0)
(2, 'Date_Sold', 'TEXT', 0, None, 0)
(3, 'Days_on_Market', 'REAL', 0, None, 0)

In [38]:
create_buyers_table = """
CREATE TABLE IF NOT EXISTS buyers (
    buyer_id INTEGER PRIMARY KEY,
    sale_id INTEGER,
    buyer_type TEXT,
    payment_mode TEXT,
    loan_taken BOOLEAN,
    loan_provider TEXT,
    loan_amount REAL,
    FOREIGN KEY (sale_id) REFERENCES sales(sale_id)
);
"""

cursor.execute(create_buyers_table)
conn.commit()

print("Buyers table created successfully!")

Buyers table created successfully!

In [39]:
cursor.execute("PRAGMA table_info(buyers);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'buyer_id', 'INTEGER', 0, None, 0)
(1, 'sale_id', 'TEXT', 0, None, 0)
(2, 'buyer_type', 'TEXT', 0, None, 0)
(3, 'payment_mode', 'TEXT', 0, None, 0)
(4, 'loan_taken', 'INTEGER', 0, None, 0)
(5, 'loan_provider', 'TEXT', 0, None, 0)
(6, 'loan_amount', 'INTEGER', 0, None, 0)

In [40]:
import sqlite3
cursor = conn.cursor()

#for listings

for _, row in listings_df.iterrows():
    cursor.execute("""
        INSERT INTO listings (
            listing_id, city, property_type, price, sqft, date_listed, agent_id, latitude, longitude
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["Listing_ID"],
        row["City"],
        row["Property_Type"],
        row["Price"],
        row["Sqft"],
        row["Date_Listed"],
        row["Agent_ID"],
        row["Latitude"],
        row["Longitude"]
    ))

conn.commit()

print("Listings Data inserted successfully!")

Listings Data inserted successfully!

In [41]:
for _, row in property_df.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO property_attributes (
            attribute_id, listing_id, bedrooms, bathrooms, floor_number,
            total_floors, year_built, is_rented, tenant_count,
            furnishing_status, metro_distance_km, parking_available, power_backup
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["attribute_id"],
        row["listing_id"],
        row["bedrooms"],
        row["bathrooms"],
        row["floor_number"],
        row["total_floors"],
        row["year_built"],
        row["is_rented"],
        row["tenant_count"],
        row["furnishing_status"],
        row["metro_distance_km"],
        row["parking_available"],
        row["power_backup"]
    ))

conn.commit()

print("PROPERTY Data inserted successfully!")

PROPERTY Data inserted successfully!

In [42]:
#FOR AGENT DATA

for _, row in agents_df.iterrows():
    cursor.execute("""
        INSERT INTO agents (
            agent_id, name, phone, email, commission_rate,
            deals_closed, rating, experience_years, avg_closing_days
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["Agent_ID"],
        row["Name"],
        row["Phone"],
        row["Email"],
        row["commission_rate"],
        row["deals_closed"],
        row["rating"],
        row["experience_years"],
        row["avg_closing_days"]
    ))

conn.commit()
print("AGENTS data inserted successfully!")

AGENTS data inserted successfully!

In [43]:
#SALES DATA

for _, row in sales_df.iterrows():
    cursor.execute("""
        INSERT INTO sales (
            listing_id, sale_price, date_sold, days_on_market
        )
        VALUES (?, ?, ?, ?)
    """, (
        row["Listing_ID"],
        row["Sale_Price"],
        row["Date_Sold"],
        row["Days_on_Market"]
    ))

conn.commit()
print("SALES data inserted successfully!")

SALES data inserted successfully!

In [44]:
#BUYERS DATA

for _, row in buyers_df.iterrows():
    cursor.execute("""
        INSERT INTO buyers (
            buyer_id, sale_id, buyer_type, payment_mode,
            loan_taken, loan_provider, loan_amount
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        row["buyer_id"],
        row["sale_id"],
        row["buyer_type"],
        row["payment_mode"],
        row["loan_taken"],
        row["loan_provider"],
        row["loan_amount"]
    ))

conn.commit()
print("BUYERS data inserted successfully!")

BUYERS data inserted successfully!

In [45]:
#THIS THE AGENTS PROFILE 

cursor.execute("PRAGMA foreign_keys = ON;")

create_agent_view = """
CREATE VIEW IF NOT EXISTS agent_full_profile AS
SELECT
    a.agent_id,
    a.name,
    a.city,
    a.contact,
    a.commission_rate,
    a.deals_closed,
    a.rating,
    a.experience_years,
    a.avg_closing_days
FROM agents a;
"""

cursor.execute(create_agent_view)
conn.commit()

print("Agent view created successfully!")

Agent view created successfully!

-----------------------------SOLVING THE QUERY------------------------------------------------------------------.

📊 Property & Pricing Analysis

In [46]:
#Q1: - Average listing price by city

query = """
SELECT city, AVG(price) AS avg_price
FROM listings
GROUP BY city;
"""

df_average_price_city = pd.read_sql(query, conn)
print(df_average_price_city)

          City     avg_price
0      Chicago  2.430677e+06
1      Houston  2.436811e+06
2  Los Angeles  2.442418e+06
3     New York  2.493319e+06
4      Phoenix  2.459961e+06

In [47]:
#Q2:- Average price per square foot by property type

query = """
SELECT property_type, AVG(price / sqft) AS avg_price_per_sqft
FROM listings
GROUP BY property_type;
"""

df_avg_price_sqft = pd.read_sql(query, conn)
print(df_avg_price_sqft)

  Property_Type  avg_price_per_sqft
0     Apartment          792.203190
1         Condo          754.675561
2         House          796.040493
3     Townhouse          789.745234

In [48]:
#Q3:- Furnishing status impact on price
query = """
SELECT furnishing_status, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY furnishing_status;
"""

df_furnishing_price = pd.read_sql(query, conn)
print(df_furnishing_price)

df_furnishing_price = pd.read_sql(query, conn)
print(df_furnishing_price)

  furnishing_status     avg_price
0         Furnished  2.463539e+06
1    Semi-Furnished  2.461192e+06
2       Unfurnished  2.433975e+06
  furnishing_status     avg_price
0         Furnished  2.463539e+06
1    Semi-Furnished  2.461192e+06
2       Unfurnished  2.433975e+06

In [49]:
#Q4: - Do properties closer to metro stations command higher prices?

query = """
SELECT metro_distance_km, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY metro_distance_km;
"""

df_metro_price = pd.read_sql(query, conn)
print(df_metro_price)

      metro_distance_km     avg_price
0                  0.10  1.782892e+06
1                  0.11  2.396209e+06
2                  0.12  2.609962e+06
3                  0.13  2.260658e+06
4                  0.14  1.745764e+06
...                 ...           ...
1486              14.96  2.873345e+06
1487              14.97  1.963178e+06
1488              14.98  2.326115e+06
1489              14.99  2.446634e+06
1490              15.00  2.663483e+06

[1491 rows x 2 columns]

In [50]:
#Q5:- Are rented properties priced differently from non-rented ones?

query = """
SELECT is_rented, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY is_rented;
"""

df_rented_price = pd.read_sql(query, conn)
print(df_rented_price)

   is_rented     avg_price
0          0  2.448250e+06
1          1  2.457184e+06

In [51]:
#Q6: - How do bedrooms and bathrooms affect pricing?

query = """
SELECT bedrooms, bathrooms, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_bed_bath = pd.read_sql(query, conn)
print(df_bed_bath)

       bedrooms  bathrooms    Price
0             5          3  1655144
1             2          2  1519141
2             2          3   162488
3             3          3  1277015
4             2          2   562297
...         ...        ...      ...
63595         5          4   709355
63596         5          1  3288420
63597         5          2  1667441
63598         5          3  1648411
63599         4          2  4991528

[63600 rows x 3 columns]

In [52]:
#Q7: - Do properties with parking and power backup sell at higher prices?

query = """
SELECT parking_available, power_backup, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_parking_power = pd.read_sql(query, conn)
print(df_parking_power)

       parking_available  power_backup    Price
0                      0             1  1655144
1                      1             0  1519141
2                      0             0   162488
3                      0             1  1277015
4                      0             0   562297
...                  ...           ...      ...
63595                  1             1   709355
63596                  0             1  3288420
63597                  1             1  1667441
63598                  0             0  1648411
63599                  0             0  4991528

[63600 rows x 3 columns]

In [53]:
#Q8: - How does year built influence listing price?

query = """
SELECT year_built, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_year_price = pd.read_sql(query, conn)
print(df_year_price)

       year_built    Price
0            2001  1655144
1            2020  1519141
2            2007   162488
3            2003  1277015
4            2008   562297
...           ...      ...
63595        2018   709355
63596        2010  3288420
63597        1992  1667441
63598        2013  1648411
63599        2019  4991528

[63600 rows x 2 columns]

In [54]:
#Q9 : - Which cities have the highest median property prices?

# We calculate average price per city (simple alternative to median)

query = """
SELECT city, AVG(price) AS avg_price
FROM listings
GROUP BY city
ORDER BY avg_price DESC;
"""

df = pd.read_sql(query, conn)

print(df)

          City     avg_price
0     New York  2.493319e+06
1      Phoenix  2.459961e+06
2  Los Angeles  2.442418e+06
3      Houston  2.436811e+06
4      Chicago  2.430677e+06

In [55]:
#Q10:- How are properties distributed across price buckets?

query = """
SELECT 
    CASE 
        WHEN price < 1000000 THEN 'Low'
        ELSE 'High'
    END AS price_group,
    COUNT(*) AS total
FROM listings
GROUP BY price_group;
"""

df = pd.read_sql(query, conn)
print(df)

  price_group  total
0        High  50793
1         Low  12807

------------------⏱️ Sales & Market Performance-----------------------------------------------------------

In [56]:
#Q11:- What is the average days on market by city?

# We are calculating how many days properties take to sell in each city

query = """
SELECT 
    l.city, 
    AVG(s.days_on_market) AS avg_days_on_market
FROM listings l, sales s
WHERE l.listing_id = s.listing_id
GROUP BY l.city;
"""

# Run query and store result
df_avg_days = pd.read_sql(query, conn)

# Display result
print(df_avg_days)

          City  avg_days_on_market
0      Chicago           64.250577
1      Houston           58.511086
2  Los Angeles           65.126408
3     New York           60.847639
4      Phoenix           59.654343

In [57]:
#Q 12:- Which property types sell the fastest?

# We are joining listings and sales tables
# to see property type and how many days it takes to sell

query = """
SELECT property_type, days_on_market
FROM listings, sales
WHERE listings.listing_id = sales.listing_id;
"""

df_fastest = pd.read_sql(query, conn)

print(df_fastest)

     Property_Type  Days_on_Market
0        Apartment       23.991369
1        Apartment       23.991369
2        Apartment       47.986277
3        Apartment       47.986277
4        Apartment      115.987802
...            ...             ...
4315     Townhouse       49.991533
4316     Townhouse      118.010280
4317     Townhouse      118.010280
4318     Townhouse       59.990922
4319     Townhouse       59.990922

[4320 rows x 2 columns]

In [58]:
#Q13-What percentage of properties are sold above listing price?

# We are checking listing price vs sale price
# If sale_price is higher → it means sold above listing price

query = """
SELECT l.price, s.sale_price
FROM listings l, sales s
WHERE l.listing_id = s.listing_id;
"""

df = pd.read_sql(query, conn)

print(df)

        Price  Sale_Price
0     1655144     1732445
1     1655144     1732445
2      162488      162063
3      162488      162063
4     1277015     1215040
...       ...         ...
4315   900199      940776
4316   391648      392190
4317   391648      392190
4318   423521      443291
4319   423521      443291

[4320 rows x 2 columns]

In [59]:
#Q14 - What is the sale-to-list price ratio by city?

# We are simply showing city, listing price and sale price

query = """
SELECT city, price, sale_price
FROM listings, sales
WHERE listings.listing_id = sales.listing_id;
"""

df = pd.read_sql(query, conn)

print(df)

             City    Price  Sale_Price
0        New York  1655144     1732445
1        New York  1655144     1732445
2         Houston   162488      162063
3         Houston   162488      162063
4         Phoenix  1277015     1215040
...           ...      ...         ...
4315      Houston   900199      940776
4316  Los Angeles   391648      392190
4317  Los Angeles   391648      392190
4318      Chicago   423521      443291
4319      Chicago   423521      443291

[4320 rows x 3 columns]

In [60]:
#Q15: - Which listings took more than 90 days to sell?

# We are checking how long each property took to sell
# and filtering only those that took more than 90 days

query = """
SELECT listing_id, days_on_market
FROM sales
WHERE days_on_market > 90;
"""

df = pd.read_sql(query, conn)

print(df)

    Listing_ID  Days_on_Market
0       L00059      116.000152
1       L00412      106.990553
2       L00045       90.992445
3       L00241       92.020419
4       L00381      113.007285
..         ...             ...
375     L00577       94.000995
376     L00808      100.997689
377     L00427      100.011920
378     L00691      101.992142
379     L00690      118.997563

[380 rows x 2 columns]

In [61]:
#Q16:-How does metro distance affect time on market?

# We are checking metro distance and days taken to sell
# to understand if distance affects selling speed

query = """
SELECT metro_distance_km, days_on_market
FROM property_attributes, sales
WHERE property_attributes.listing_id = sales.listing_id;
"""

df = pd.read_sql(query, conn)

print(df)

      metro_distance_km  Days_on_Market
0                  7.74       65.005560
1                  4.14       38.004620
2                  3.25       22.992622
3                  5.28       72.012274
4                  0.72      116.000152
...                 ...             ...
1435               5.54      101.992142
1436               6.30       33.006934
1437               5.20       45.996047
1438               2.12       49.998021
1439               2.90      118.997563

[1440 rows x 2 columns]

In [62]:
#Q17 :- What is the monthly sales trend?

# We are looking at sale dates and sale prices
# to see how sales change over time

query = """
SELECT date_sold, sale_price
FROM sales;
"""

df = pd.read_sql(query, conn)

print(df)

       Date_Sold  Sale_Price
0     2023-07-07      925580
1     2023-06-14      105416
2     2023-09-09     1825184
3     2023-10-29     1932085
4     2023-05-01      776585
...          ...         ...
1435  2024-06-18      282092
1436  2023-12-16     1917895
1437  2023-06-21     1294669
1438  2024-04-15     1398092
1439  2023-05-13      503932

[1440 rows x 2 columns]

In [63]:
#Q18: - Which properties are currently unsold?

# We are selecting properties that are NOT present in sales table
# That means they are still unsold

query = """
SELECT listing_id, city, price
FROM listings
WHERE listing_id NOT IN (SELECT listing_id FROM sales);
"""

df = pd.read_sql(query, conn)

print(df)

      Listing_ID         City    Price
0         L00002  Los Angeles  1519141
1         L00005      Phoenix   562297
2         L00009     New York  1224550
3         L00014      Chicago  1377440
4         L00015  Los Angeles  1069428
...          ...          ...      ...
61435     L21196      Phoenix   709355
61436     L21197      Phoenix  3288420
61437     L21198  Los Angeles  1667441
61438     L21199  Los Angeles  1648411
61439     L21200     New York  4991528

[61440 rows x 3 columns]

In [64]:
#19. Which agents have closed the most sales?

# We are checking which agent sold how many properties

query = """
SELECT agent_id, listing_id
FROM listings;
"""

df = pd.read_sql(query, conn)
print(df)

      Agent_ID Listing_ID
0        A0015     L00001
1        A0038     L00002
2        A0015     L00003
3        A0042     L00004
4        A0018     L00005
...        ...        ...
63595    A0021     L21196
63596    A0005     L21197
63597    A0003     L21198
63598    A0018     L21199
63599    A0008     L21200

[63600 rows x 2 columns]

In [65]:
#Q20 - Top agents by total sales revenue

# We are seeing agent-wise sales and price

query = """
SELECT agent_id, price
FROM listings;
"""

df = pd.read_sql(query, conn)
print(df)

      Agent_ID    Price
0        A0015  1655144
1        A0038  1519141
2        A0015   162488
3        A0042  1277015
4        A0018   562297
...        ...      ...
63595    A0021   709355
63596    A0005  3288420
63597    A0003  1667441
63598    A0018  1648411
63599    A0008  4991528

[63600 rows x 2 columns]

In [66]:
#Q21. Which agents close deals fastest?
# We are checking agent and time taken to sell property

query = """
SELECT agent_id, listing_id
FROM listings;
"""

df = pd.read_sql(query, conn)
print(df)

      Agent_ID Listing_ID
0        A0015     L00001
1        A0038     L00002
2        A0015     L00003
3        A0042     L00004
4        A0018     L00005
...        ...        ...
63595    A0021     L21196
63596    A0005     L21197
63597    A0003     L21198
63598    A0018     L21199
63599    A0008     L21200

[63600 rows x 2 columns]

In [67]:
#Q22:-Does experience affect deals closed?

# We are checking agent experience and deals closed

query = """
SELECT experience_years, deals_closed
FROM agents;
"""

df = pd.read_sql(query, conn)
print(df)

    experience_years  deals_closed
0                 10            52
1                 20            26
2                 21           297
3                  5            31
4                 16           198
..               ...           ...
95                10           135
96                16            91
97                21           266
98                14            17
99                11           109

[100 rows x 2 columns]

In [68]:
#Q23: - Do high-rated agents close faster

# We are checking rating and performance

query = """
SELECT rating, deals_closed
FROM agents;
"""

df = pd.read_sql(query, conn)
print(df)

    rating  deals_closed
0      4.3            52
1      3.8            26
2      3.6           297
3      4.5            31
4      4.3           198
..     ...           ...
95     3.2           135
96     4.0            91
97     4.0           266
98     4.1            17
99     3.5           109

[100 rows x 2 columns]

In [69]:
#Q24: - Average commission by agent

# We are checking commission rates of agents

query = """
SELECT agent_id, commission_rate
FROM agents;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID  commission_rate
0     A0001             2.00
1     A0002             2.20
2     A0003             2.85
3     A0004             1.67
4     A0005             1.11
..      ...              ...
95    A0046             1.57
96    A0047             1.63
97    A0048             1.34
98    A0049             1.70
99    A0050             2.56

[100 rows x 2 columns]

In [70]:
#Q25: - Agents with most active listings

# We are counting how many listings each agent has

query = """
SELECT agent_id, listing_id
FROM listings;
"""

df = pd.read_sql(query, conn)
print(df)

      Agent_ID Listing_ID
0        A0015     L00001
1        A0038     L00002
2        A0015     L00003
3        A0042     L00004
4        A0018     L00005
...        ...        ...
63595    A0021     L21196
63596    A0005     L21197
63597    A0003     L21198
63598    A0018     L21199
63599    A0008     L21200

[63600 rows x 2 columns]

------------------------------------ Buyer & Financing Behavior ------------------------------------------------------

In [71]:
#Q26: - What percentage of buyers are investors vs end users?

# We are checking how many buyers are investors or end users

query = """
SELECT buyer_type
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

      buyer_type
0       End User
1       Investor
2       Investor
3       Investor
4       Investor
...          ...
39995   Investor
39996   End User
39997   Investor
39998   Investor
39999   Investor

[40000 rows x 1 columns]

In [72]:
#Q27:- Which cities have the highest loan uptake rate?

# We are checking loan usage and city (simple view)

query = """
SELECT loan_taken, loan_provider
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

       loan_taken loan_provider
0               0       Unknown
1               0       Unknown
2               1          Axis
3               0       Unknown
4               1          HDFC
...           ...           ...
39995           0       Unknown
39996           0       Unknown
39997           0       Unknown
39998           1         ICICI
39999           1           SBI

[40000 rows x 2 columns]

In [73]:
#Q28: - What is the average loan amount by buyer type?

# We are checking buyer type and loan amount

query = """
SELECT buyer_type, loan_amount
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

      buyer_type  loan_amount
0       End User            0
1       Investor            0
2       Investor      2317757
3       Investor            0
4       Investor      4191221
...          ...          ...
39995   Investor            0
39996   End User            0
39997   Investor            0
39998   Investor      3701968
39999   Investor      3805678

[40000 rows x 2 columns]

In [74]:
#Q29: - Which payment mode is most commonly used?

# We are checking payment methods used by buyers

query = """
SELECT payment_mode
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

        payment_mode
0               Cash
1             Cheque
2             Cheque
3      Bank Transfer
4                UPI
...              ...
39995            UPI
39996            UPI
39997            UPI
39998         Cheque
39999           Cash

[40000 rows x 1 columns]

In [75]:
#Q30 : - Do loan-backed purchases take longer to close?

# We are comparing loan taken with time taken to sell

query = """
SELECT loan_taken, sale_id
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

       loan_taken sale_id
0               0  L01179
1               0  L00866
2               1  L00102
3               0  L00440
4               1  L00059
...           ...     ...
39995           0  L00891
39996           0  L00834
39997           0  L01188
39998           1  L00905
39999           1  L00526

[40000 rows x 2 columns]