In [2]:
import pandas as pd
import json
import sqlite3

In [3]:
# reading the json and csv files
listings_df = pd.read_json("C:/Users/HP/Downloads/listings_final_expanded.json")

In [4]:
property_df = pd.read_json("C:/Users/HP/Downloads/property_attributes_final_expanded.json")

In [5]:
agents_df = pd.read_json("C:/Users/HP/Downloads/agents_cleaned.json")

In [6]:
sales_df = pd.read_csv("C:/Users/HP/Downloads/sales_cleaned.csv")

In [7]:
buyers_df = pd.read_json("C:/Users/HP/Downloads/buyers_cleaned.json")

In [8]:
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [9]:
property_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [10]:
agents_df.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [11]:
sales_df.head()

#CHANGING THE FORMAT OF PRICE FROM SCIENTIFIC ANNOTATION TO INTEGER.  
sales_df["Sale_Price"] = sales_df["Sale_Price"].astype(int)

In [12]:
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [13]:
#checking wheather null value is there.
listings_df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [14]:
print(property_df.isnull().sum())

attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

In [15]:
print(agents_df.isnull().sum())

Agent_ID            0
Name                0
Phone               0
Email               0
commission_rate     0
deals_closed        0
rating              0
experience_years    0
avg_closing_days    0
dtype: int64

In [16]:
print(sales_df.isnull().sum())

Listing_ID        0
Sale_Price        0
Date_Sold         0
Days_on_Market    0
dtype: int64

In [17]:
print(buyers_df.isnull().sum())

buyer_id            0
sale_id             0
buyer_type          0
payment_mode        0
loan_taken          0
loan_provider    9966
loan_amount         0
dtype: int64

In [18]:
for col in buyers_df.columns:
    if buyers_df[col].dtype == "object":
        buyers_df[col].fillna("Unknown", inplace=True)
    else:
        buyers_df[col].fillna(buyers_df[col].median(), inplace=True)

In [19]:
print(buyers_df.isnull().sum())

buyer_id         0
sale_id          0
buyer_type       0
payment_mode     0
loan_taken       0
loan_provider    0
loan_amount      0
dtype: int64

In [20]:
conn = sqlite3.connect("realestate.db")   # creates database file
cursor = conn.cursor()

print("Connected to SQLite")

Connected to SQLite

In [21]:
listings_df.to_sql("listings", conn, if_exists="replace", index=False)

21200

In [22]:
listings_df = pd.read_sql("SELECT * FROM listings", conn)
print(listings_df.head())

  Listing_ID         City Property_Type         Price         Sqft  \
0     L00001     New York     Apartment  1.655144e+06  2753.009121
1     L00002  Los Angeles     Apartment  1.519141e+06  4966.988193
2     L00003      Houston     Apartment  1.624890e+05  1267.003959
3     L00004      Phoenix     Apartment  1.277016e+06  2128.014429
4     L00005      Phoenix     Townhouse  5.622970e+05  4178.997421

  Date_Listed Agent_ID   Latitude   Longitude
0  2023-05-06    A0015  33.965208  -69.861589
1  2023-02-14    A0038  42.547892  -90.277860
2  2023-04-22    A0015  28.732327 -115.952982
3  2024-01-02    A0042  26.403938  -74.771490
4  2023-10-29    A0018  39.425252  -83.917878

In [23]:
# Property table
property_df.to_sql("property", conn, if_exists="replace", index=False)

# Agents table
agents_df.to_sql("agents", conn, if_exists="replace", index=False)

# Sales table
sales_df.to_sql("sales", conn, if_exists="replace", index=False)

# Buyers table
buyers_df.to_sql("buyers", conn, if_exists="replace", index=False)

print("All tables created successfully!")

All tables created successfully!

In [24]:
property_df = pd.read_sql("SELECT * FROM property", conn)
print(property_df.head())

   attribute_id listing_id  bedrooms  bathrooms  floor_number  total_floors  \
0             1     L00001         5          3             9             9
1             2     L00002         2          2            19            29
2             3     L00003         2          3             8            26
3             4     L00004         3          3            25            10
4             5     L00005         2          2            15            16

   year_built  is_rented  tenant_count furnishing_status  metro_distance_km  \
0        2001          1             4         Furnished               7.26
1        2020          0             0       Unfurnished               4.84
2        2007          1             4    Semi-Furnished               4.92
3        2003          0             3         Furnished               1.20
4        2008          1             1    Semi-Furnished               7.90

   parking_available  power_backup
0                  0             1
1                  1             0
2                  0             0
3                  0             1
4                  0             0

In [25]:
property_df = pd.read_sql("SELECT * FROM property", conn)
print(property_df.head())

   attribute_id listing_id  bedrooms  bathrooms  floor_number  total_floors  \
0             1     L00001         5          3             9             9
1             2     L00002         2          2            19            29
2             3     L00003         2          3             8            26
3             4     L00004         3          3            25            10
4             5     L00005         2          2            15            16

   year_built  is_rented  tenant_count furnishing_status  metro_distance_km  \
0        2001          1             4         Furnished               7.26
1        2020          0             0       Unfurnished               4.84
2        2007          1             4    Semi-Furnished               4.92
3        2003          0             3         Furnished               1.20
4        2008          1             1    Semi-Furnished               7.90

   parking_available  power_backup
0                  0             1
1                  1             0
2                  0             0
3                  0             1
4                  0             0

In [26]:
agents_df = pd.read_sql("SELECT * FROM agents", conn)
print(agents_df.head())

  Agent_ID         Name            Phone                 Email  \
0    A0001  Agent A0001  +1-534-665-8373  a0001@realestate.com
1    A0002  Agent A0002  +1-493-463-4698  a0002@realestate.com
2    A0003  Agent A0003  +1-290-534-1121  a0003@realestate.com
3    A0004  Agent A0004  +1-691-610-4878  a0004@realestate.com
4    A0005  Agent A0005  +1-829-613-5411  a0005@realestate.com

   commission_rate  deals_closed  rating  experience_years  avg_closing_days
0             2.00            52     4.3                10                64
1             2.20            26     3.8                20                82
2             2.85           297     3.6                21                83
3             1.67            31     4.5                 5                61
4             1.11           198     4.3                16                67

In [27]:
sales_df = pd.read_sql("SELECT * FROM sales", conn)
print(sales_df.head())

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776585  2023-05-01      116.000152

In [28]:
buyers_df = pd.read_sql("SELECT * FROM buyers", conn)
print(buyers_df.head())

   buyer_id sale_id buyer_type   payment_mode  loan_taken loan_provider  \
0         1  L01179   End User           Cash           0       Unknown
1         2  L00866   Investor         Cheque           0       Unknown
2         3  L00102   Investor         Cheque           1          Axis
3         4  L00440   Investor  Bank Transfer           0       Unknown
4         5  L00059   Investor            UPI           1          HDFC

   loan_amount
0            0
1            0
2      2317757
3            0
4      4191221

In [29]:
from IPython.display import display

display("The Listing Data is:",listings_df.head())
display("The Property Data is:",property_df.head())
display("The Agents Data is:",agents_df.head())
display("The Sales Data is:",sales_df.head())
display("The Buyers Data is:",buyers_df.head())

'The Listing Data is:'

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

'The Property Data is:'

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,1,4,Furnished,7.26,0,1
1,2,L00002,2,2,19,29,2020,0,0,Unfurnished,4.84,1,0
2,3,L00003,2,3,8,26,2007,1,4,Semi-Furnished,4.92,0,0
3,4,L00004,3,3,25,10,2003,0,3,Furnished,1.20,0,1
4,5,L00005,2,2,15,16,2008,1,1,Semi-Furnished,7.90,0,0

'The Agents Data is:'

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

'The Sales Data is:'

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776585  2023-05-01      116.000152

'The Buyers Data is:'

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,0,Unknown,0
1,2,L00866,Investor,Cheque,0,Unknown,0
2,3,L00102,Investor,Cheque,1,Axis,2317757
3,4,L00440,Investor,Bank Transfer,0,Unknown,0
4,5,L00059,Investor,UPI,1,HDFC,4191221

In [30]:
create_table_listing = """ 
CREATE TABLE IF NOT EXISTS listings (
    Listing_ID TEXT PRIMARY KEY, 
    Address TEXT,
    City TEXT,
    State TEXT,
    Zip TEXT,
    Property_Type TEXT,
    Price REAL,
    Area_sqft REAL,
    Agent_ID TEXT, 
    Listed_Date TEXT, 
    FOREIGN KEY (Agent_ID) REFERENCES agents(Agent_ID)
);
""" 

cursor.execute(create_table_listing)
conn.commit()

print("Listings table created successfully!")

Listings table created successfully!

In [31]:
listings_df.to_sql("listings", conn, if_exists="append", index=False)

21200

In [32]:
cursor.execute("PRAGMA table_info(listings);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Listing_ID', 'TEXT', 0, None, 0)
(1, 'City', 'TEXT', 0, None, 0)
(2, 'Property_Type', 'TEXT', 0, None, 0)
(3, 'Price', 'REAL', 0, None, 0)
(4, 'Sqft', 'REAL', 0, None, 0)
(5, 'Date_Listed', 'TEXT', 0, None, 0)
(6, 'Agent_ID', 'TEXT', 0, None, 0)
(7, 'Latitude', 'REAL', 0, None, 0)
(8, 'Longitude', 'REAL', 0, None, 0)

In [33]:
create_property_attributes_table = """ 
CREATE TABLE IF NOT EXISTS property_attributes ( 
    attribute_id INTEGER PRIMARY KEY, 
    listing_id TEXT UNIQUE,
    bedrooms INTEGER,
    bathrooms INTEGER,
    floor_number INTEGER,
    total_floors INTEGER,
    year_built INTEGER,
    is_rented BOOLEAN, 
    tenant_count INTEGER,
    furnishing_status TEXT,
    metro_distance_km REAL,
    parking_available BOOLEAN,
    power_backup BOOLEAN, 
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""

cursor.execute(create_property_attributes_table) 
conn.commit()

print("Property table created successfully!")

Property table created successfully!

In [34]:
cursor.execute("PRAGMA table_info(property);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'attribute_id', 'INTEGER', 0, None, 0)
(1, 'listing_id', 'TEXT', 0, None, 0)
(2, 'bedrooms', 'INTEGER', 0, None, 0)
(3, 'bathrooms', 'INTEGER', 0, None, 0)
(4, 'floor_number', 'INTEGER', 0, None, 0)
(5, 'total_floors', 'INTEGER', 0, None, 0)
(6, 'year_built', 'INTEGER', 0, None, 0)
(7, 'is_rented', 'INTEGER', 0, None, 0)
(8, 'tenant_count', 'INTEGER', 0, None, 0)
(9, 'furnishing_status', 'TEXT', 0, None, 0)
(10, 'metro_distance_km', 'REAL', 0, None, 0)
(11, 'parking_available', 'INTEGER', 0, None, 0)
(12, 'power_backup', 'INTEGER', 0, None, 0)

In [35]:
create_agents_table = """
CREATE TABLE IF NOT EXISTS agents (
    agent_id INTEGER PRIMARY KEY, 
    name TEXT,
    phone INT,
    commission_rate REAL,
    deals_closed INTEGER,
    rating REAL,
    experience_years INTEGER,
    avg_closing_days INTEGER,
    FOREIGN KEY(agent_id) REFERENCES agents(agent_id)
);
"""

cursor.execute(create_agents_table)
conn.commit()

print("Agents table created successfully!")

Agents table created successfully!

In [36]:
cursor.execute("PRAGMA table_info(agents);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Agent_ID', 'TEXT', 0, None, 0)
(1, 'Name', 'TEXT', 0, None, 0)
(2, 'Phone', 'TEXT', 0, None, 0)
(3, 'Email', 'TEXT', 0, None, 0)
(4, 'commission_rate', 'REAL', 0, None, 0)
(5, 'deals_closed', 'INTEGER', 0, None, 0)
(6, 'rating', 'REAL', 0, None, 0)
(7, 'experience_years', 'INTEGER', 0, None, 0)
(8, 'avg_closing_days', 'INTEGER', 0, None, 0)

In [37]:
create_sales_table = """
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id TEXT,
    sale_price REAL,
    date_sold TEXT,
    days_on_market REAL,
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""

cursor.execute(create_sales_table)
conn.commit()

print("Sales table created successfully!")

Sales table created successfully!

In [38]:
cursor.execute("PRAGMA table_info(sales);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'Listing_ID', 'TEXT', 0, None, 0)
(1, 'Sale_Price', 'INTEGER', 0, None, 0)
(2, 'Date_Sold', 'TEXT', 0, None, 0)
(3, 'Days_on_Market', 'REAL', 0, None, 0)

In [39]:
create_buyers_table = """
CREATE TABLE IF NOT EXISTS buyers (
    buyer_id INTEGER PRIMARY KEY,
    sale_id INTEGER,
    buyer_type TEXT,
    payment_mode TEXT,
    loan_taken BOOLEAN,
    loan_provider TEXT,
    loan_amount REAL,
    FOREIGN KEY (sale_id) REFERENCES sales(sale_id)
);
"""

cursor.execute(create_buyers_table)
conn.commit()

print("Buyers table created successfully!")

Buyers table created successfully!

In [40]:
cursor.execute("PRAGMA table_info(buyers);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'buyer_id', 'INTEGER', 0, None, 0)
(1, 'sale_id', 'TEXT', 0, None, 0)
(2, 'buyer_type', 'TEXT', 0, None, 0)
(3, 'payment_mode', 'TEXT', 0, None, 0)
(4, 'loan_taken', 'INTEGER', 0, None, 0)
(5, 'loan_provider', 'TEXT', 0, None, 0)
(6, 'loan_amount', 'INTEGER', 0, None, 0)

In [41]:
import sqlite3
cursor = conn.cursor()

#for listings

for _, row in listings_df.iterrows():
    cursor.execute("""
        INSERT INTO listings (
            listing_id, city, property_type, price, sqft, date_listed, agent_id, latitude, longitude
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["Listing_ID"],
        row["City"],
        row["Property_Type"],
        row["Price"],
        row["Sqft"],
        row["Date_Listed"],
        row["Agent_ID"],
        row["Latitude"],
        row["Longitude"]
    ))

conn.commit()

print("Listings Data inserted successfully!")

Listings Data inserted successfully!

In [42]:
for _, row in property_df.iterrows():
    cursor.execute("""
        INSERT OR IGNORE INTO property_attributes (
            attribute_id, listing_id, bedrooms, bathrooms, floor_number,
            total_floors, year_built, is_rented, tenant_count,
            furnishing_status, metro_distance_km, parking_available, power_backup
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["attribute_id"],
        row["listing_id"],
        row["bedrooms"],
        row["bathrooms"],
        row["floor_number"],
        row["total_floors"],
        row["year_built"],
        row["is_rented"],
        row["tenant_count"],
        row["furnishing_status"],
        row["metro_distance_km"],
        row["parking_available"],
        row["power_backup"]
    ))

conn.commit()

print("PROPERTY Data inserted successfully!")

PROPERTY Data inserted successfully!

In [43]:
#FOR AGENT DATA

for _, row in agents_df.iterrows():
    cursor.execute("""
        INSERT INTO agents (
            agent_id, name, phone, email, commission_rate,
            deals_closed, rating, experience_years, avg_closing_days
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["Agent_ID"],
        row["Name"],
        row["Phone"],
        row["Email"],
        row["commission_rate"],
        row["deals_closed"],
        row["rating"],
        row["experience_years"],
        row["avg_closing_days"]
    ))

conn.commit()
print("AGENTS data inserted successfully!")

AGENTS data inserted successfully!

In [44]:
#SALES DATA

for _, row in sales_df.iterrows():
    cursor.execute("""
        INSERT INTO sales (
            listing_id, sale_price, date_sold, days_on_market
        )
        VALUES (?, ?, ?, ?)
    """, (
        row["Listing_ID"],
        row["Sale_Price"],
        row["Date_Sold"],
        row["Days_on_Market"]
    ))

conn.commit()
print("SALES data inserted successfully!")

SALES data inserted successfully!

In [45]:
#BUYERS DATA

for _, row in buyers_df.iterrows():
    cursor.execute("""
        INSERT INTO buyers (
            buyer_id, sale_id, buyer_type, payment_mode,
            loan_taken, loan_provider, loan_amount
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        row["buyer_id"],
        row["sale_id"],
        row["buyer_type"],
        row["payment_mode"],
        row["loan_taken"],
        row["loan_provider"],
        row["loan_amount"]
    ))

conn.commit()
print("BUYERS data inserted successfully!")

BUYERS data inserted successfully!

In [46]:
#THIS THE AGENTS PROFILE 

cursor.execute("PRAGMA foreign_keys = ON;")

create_agent_view = """
CREATE VIEW IF NOT EXISTS agent_full_profile AS
SELECT
    a.agent_id,
    a.name,
    a.city,
    a.contact,
    a.commission_rate,
    a.deals_closed,
    a.rating,
    a.experience_years,
    a.avg_closing_days
FROM agents a;
"""

cursor.execute(create_agent_view)
conn.commit()

print("Agent view created successfully!")

Agent view created successfully!

-----------------------------SOLVING THE QUERY------------------------------------------------------------------.

📊 Property & Pricing Analysis

In [47]:
#Q1: - Average listing price by city

query = """
SELECT city, AVG(price) AS avg_price
FROM listings
GROUP BY city;
"""

df_average_price_city = pd.read_sql(query, conn)
print(df_average_price_city)

          City     avg_price
0      Chicago  2.430678e+06
1      Houston  2.436811e+06
2  Los Angeles  2.442418e+06
3     New York  2.493320e+06
4      Phoenix  2.459962e+06

In [48]:
#Q2:- Average price per square foot by property type

query = """
SELECT property_type, AVG(price / sqft) AS avg_price_per_sqft
FROM listings
GROUP BY property_type;
"""

df_avg_price_sqft = pd.read_sql(query, conn)
print(df_avg_price_sqft)

  Property_Type  avg_price_per_sqft
0     Apartment          792.203348
1         Condo          754.675722
2         House          796.040653
3     Townhouse          789.745399

In [49]:
#Q3:- Furnishing status impact on price
query = """
SELECT furnishing_status, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY furnishing_status;
"""

df_furnishing_price = pd.read_sql(query, conn)
print(df_furnishing_price)

df_furnishing_price = pd.read_sql(query, conn)
print(df_furnishing_price)

  furnishing_status     avg_price
0         Furnished  2.463539e+06
1    Semi-Furnished  2.461193e+06
2       Unfurnished  2.433975e+06
  furnishing_status     avg_price
0         Furnished  2.463539e+06
1    Semi-Furnished  2.461193e+06
2       Unfurnished  2.433975e+06

In [50]:
#Q4: - Do properties closer to metro stations command higher prices?

query = """
SELECT metro_distance_km, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY metro_distance_km;
"""

df_metro_price = pd.read_sql(query, conn)
print(df_metro_price)

      metro_distance_km     avg_price
0                  0.10  1.782892e+06
1                  0.11  2.396209e+06
2                  0.12  2.609962e+06
3                  0.13  2.260659e+06
4                  0.14  1.745764e+06
...                 ...           ...
1486              14.96  2.873346e+06
1487              14.97  1.963179e+06
1488              14.98  2.326115e+06
1489              14.99  2.446634e+06
1490              15.00  2.663483e+06

[1491 rows x 2 columns]

In [51]:
#Q5:- Are rented properties priced differently from non-rented ones?

query = """
SELECT is_rented, AVG(price) AS avg_price
FROM listings
JOIN property_attributes
ON listings.listing_id = property_attributes.listing_id
GROUP BY is_rented;
"""

df_rented_price = pd.read_sql(query, conn)
print(df_rented_price)

   is_rented     avg_price
0          0  2.448250e+06
1          1  2.457185e+06

In [52]:
#Q6: - How do bedrooms and bathrooms affect pricing?

query = """
SELECT bedrooms, bathrooms, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_bed_bath = pd.read_sql(query, conn)
print(df_bed_bath)

        bedrooms  bathrooms         Price
0              5          3  1.655144e+06
1              5          3  1.655144e+06
2              2          2  1.519141e+06
3              2          2  1.519141e+06
4              2          3  1.624890e+05
...          ...        ...           ...
127195         5          2  1.667441e+06
127196         5          3  1.648412e+06
127197         5          3  1.648412e+06
127198         4          2  4.991528e+06
127199         4          2  4.991528e+06

[127200 rows x 3 columns]

In [53]:
#Q7: - Do properties with parking and power backup sell at higher prices?

query = """
SELECT parking_available, power_backup, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_parking_power = pd.read_sql(query, conn)
print(df_parking_power)

        parking_available  power_backup         Price
0                       0             1  1.655144e+06
1                       0             1  1.655144e+06
2                       1             0  1.519141e+06
3                       1             0  1.519141e+06
4                       0             0  1.624890e+05
...                   ...           ...           ...
127195                  1             1  1.667441e+06
127196                  0             0  1.648412e+06
127197                  0             0  1.648412e+06
127198                  0             0  4.991528e+06
127199                  0             0  4.991528e+06

[127200 rows x 3 columns]

In [54]:
#Q8: - How does year built influence listing price?

query = """
SELECT year_built, price
FROM listings, property_attributes
WHERE listings.listing_id = property_attributes.listing_id;
"""

df_year_price = pd.read_sql(query, conn)
print(df_year_price)

        year_built         Price
0             2001  1.655144e+06
1             2001  1.655144e+06
2             2020  1.519141e+06
3             2020  1.519141e+06
4             2007  1.624890e+05
...            ...           ...
127195        1992  1.667441e+06
127196        2013  1.648412e+06
127197        2013  1.648412e+06
127198        2019  4.991528e+06
127199        2019  4.991528e+06

[127200 rows x 2 columns]

In [55]:
#Q9 : - Which cities have the highest median property prices?

# We calculate average price per city (simple alternative to median)

query = """
SELECT city, AVG(price) AS avg_price
FROM listings
GROUP BY city
ORDER BY avg_price DESC;
"""

df = pd.read_sql(query, conn)

print(df)

          City     avg_price
0     New York  2.493320e+06
1      Phoenix  2.459962e+06
2  Los Angeles  2.442418e+06
3      Houston  2.436811e+06
4      Chicago  2.430678e+06

In [83]:
#Q10:- How are properties distributed across price buckets?

query = """
SELECT 
    CASE 
        WHEN price < 200000 THEN 'Under 200K'
        WHEN price < 500000 THEN '200K - 500K'
        WHEN price < 1000000 THEN '500K - 1M'
        ELSE 'Above 1M'
    END AS price_group,
    COUNT(*) AS total
FROM listings
GROUP BY price_group;
"""

df = pd.read_sql(query, conn)
print(df)

   price_group  total
0  200K - 500K   4278
1    500K - 1M   7206
2     Above 1M  50793
3   Under 200K   1323

------------------⏱️ Sales & Market Performance-----------------------------------------------------------

In [57]:
#Q11:- What is the average days on market by city?

# We are calculating how many days properties take to sell in each city

query = """
SELECT 
    l.city, 
    AVG(s.days_on_market) AS avg_days_on_market
FROM listings l, sales s
WHERE l.listing_id = s.listing_id
GROUP BY l.city;
"""

# Run query and store result
df_avg_days = pd.read_sql(query, conn)

# Display result
print(df_avg_days)

          City  avg_days_on_market
0      Chicago           64.250577
1      Houston           58.511086
2  Los Angeles           65.126408
3     New York           60.847639
4      Phoenix           59.654343

In [ ]:
#Q 12:- Which property types sell the fastest?

query = """
SELECT property_type, AVG(days_on_market) AS avg_days
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id
GROUP BY property_type;
"""

df_fastest = pd.read_sql(query, conn)

print(df_fastest)

  Property_Type   avg_days
0     Apartment  60.647493
1         Condo  66.540995
2         House  58.337921
3     Townhouse  60.963765

In [80]:
#Q13-What percentage of properties are sold above listing price?

# We are checking listing price vs sale price
# If sale_price is higher → it means sold above listing price

query = """
SELECT 
    (SUM(s.sale_price > l.price) * 100.0 / COUNT(*)) AS percentage
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id;
"""

df = pd.read_sql(query, conn)

print(df)

   percentage
0   49.305556

In [79]:
#Q14 - What is the sale-to-list price ratio by city?

# We are simply showing city, listing price and sale price

query = """
SELECT 
    l.city,
    AVG(s.sale_price * 1.0 / l.price) AS sale_to_list_ratio
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id
GROUP BY l.city;
"""

df = pd.read_sql(query, conn)
print(df)

          City  sale_to_list_ratio
0      Chicago            1.001526
1      Houston            1.000000
2  Los Angeles            0.999835
3     New York            0.999583
4      Phoenix            0.998901

In [61]:
#Q15: - Which listings took more than 90 days to sell?

# We are checking how long each property took to sell
# and filtering only those that took more than 90 days

query = """
SELECT listing_id, days_on_market
FROM sales
WHERE days_on_market > 90;
"""

df = pd.read_sql(query, conn)

print(df)

    Listing_ID  Days_on_Market
0       L00059      116.000152
1       L00412      106.990553
2       L00045       90.992445
3       L00241       92.020419
4       L00381      113.007285
..         ...             ...
375     L00577       94.000995
376     L00808      100.997689
377     L00427      100.011920
378     L00691      101.992142
379     L00690      118.997563

[380 rows x 2 columns]

In [78]:
#Q16:-How does metro distance affect time on market?

# We are checking metro distance and days taken to sell
# to understand if distance affects selling speed

query = """
SELECT 
    metro_distance_km,
    AVG(days_on_market) AS avg_days
FROM property_attributes p
JOIN sales s 
ON p.listing_id = s.listing_id
GROUP BY metro_distance_km
ORDER BY metro_distance_km;
"""

df = pd.read_sql(query, conn)

print(df)

     metro_distance_km    avg_days
0                 0.21  108.001634
1                 0.22   81.007696
2                 0.24   21.994073
3                 0.25   57.999647
4                 0.26   99.005723
..                 ...         ...
458               7.93  102.010227
459               7.94   81.996154
460               7.95   71.666221
461               7.99   64.999727
462               8.00   70.338607

[463 rows x 2 columns]

In [63]:
#Q17 :- What is the monthly sales trend?

# We are looking at sale dates and sale prices
# to see how sales change over time

query = """
SELECT 
    strftime('%Y-%m', date_sold) AS month,
    COUNT(*) AS total_sales
FROM sales
GROUP BY month
ORDER BY month;
"""

df = pd.read_sql(query, conn)

print(df)

      month  total_sales
0   2023-01           14
1   2023-02           34
2   2023-03           40
3   2023-04           72
4   2023-05           90
5   2023-06           62
6   2023-07           96
7   2023-08          100
8   2023-09           92
9   2023-10          128
10  2023-11           92
11  2023-12           84
12  2024-01           88
13  2024-02           88
14  2024-03           78
15  2024-04           58
16  2024-05           90
17  2024-06           58
18  2024-07           48
19  2024-08           26
20  2024-09            2

In [64]:
#Q18: - Which properties are currently unsold?

# We are selecting properties that are NOT present in sales table
# That means they are still unsold

query = """
SELECT listing_id, city, price
FROM listings
WHERE listing_id NOT IN (SELECT listing_id FROM sales);
"""

df = pd.read_sql(query, conn)

print(df)

      Listing_ID         City         Price
0         L00002  Los Angeles  1.519141e+06
1         L00005      Phoenix  5.622970e+05
2         L00009     New York  1.224551e+06
3         L00014      Chicago  1.377440e+06
4         L00015  Los Angeles  1.069429e+06
...          ...          ...           ...
61435     L21196      Phoenix  7.093553e+05
61436     L21197      Phoenix  3.288420e+06
61437     L21198  Los Angeles  1.667441e+06
61438     L21199  Los Angeles  1.648412e+06
61439     L21200     New York  4.991528e+06

[61440 rows x 3 columns]

In [65]:
#19. Which agents have closed the most sales?

# We are checking which agent sold how many properties

query = """
SELECT l.agent_id, COUNT(*) AS total_sales
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id
GROUP BY l.agent_id;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID  total_sales
0     A0001           90
1     A0002           48
2     A0003           96
3     A0004           66
4     A0005           60
5     A0006           90
6     A0007          114
7     A0008           66
8     A0009          102
9     A0010           90
10    A0011          144
11    A0012           66
12    A0013           42
13    A0014          126
14    A0015           96
15    A0016           90
16    A0017           84
17    A0018           78
18    A0019          102
19    A0020           60
20    A0021          102
21    A0022           54
22    A0023           72
23    A0024           84
24    A0025          102
25    A0026           72
26    A0027          108
27    A0028           60
28    A0029          108
29    A0030           66
30    A0031           78
31    A0032           60
32    A0033           96
33    A0034           42
34    A0035          126
35    A0036           96
36    A0037           72
37    A0038           72
38    A0039           96
39    A0040           78
40    A0041           90
41    A0042          150
42    A0043          120
43    A0044           48
44    A0045           78
45    A0046          120
46    A0047           84
47    A0048          114
48    A0049           60
49    A0050          102

In [66]:
#Q20 - Top agents by total sales revenue

# We are seeing agent-wise sales and price

query = """
SELECT l.agent_id, SUM(s.sale_price) AS total_revenue
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id
GROUP BY l.agent_id;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID  total_revenue
0     A0001      109043478
1     A0002       70529760
2     A0003       93509664
3     A0004       76528572
4     A0005       60686298
5     A0006       99139344
6     A0007      110486808
7     A0008       66431358
8     A0009      121675596
9     A0010       85368942
10    A0011      167293560
11    A0012       88383168
12    A0013       54686490
13    A0014      132204000
14    A0015      106517100
15    A0016       80702082
16    A0017      111503070
17    A0018       93239220
18    A0019      100383618
19    A0020       57632988
20    A0021       99289806
21    A0022       37821582
22    A0023       87809184
23    A0024       79176078
24    A0025      112911498
25    A0026       50877072
26    A0027      126598122
27    A0028       58991322
28    A0029      117518934
29    A0030       74906634
30    A0031       94339710
31    A0032       63919878
32    A0033       85212822
33    A0034       42068352
34    A0035      136354464
35    A0036      115257216
36    A0037       73889898
37    A0038       66363792
38    A0039      115338024
39    A0040       72235704
40    A0041       84464856
41    A0042      163149564
42    A0043      144614460
43    A0044       61485270
44    A0045       70914408
45    A0046      128014758
46    A0047       80869044
47    A0048      127117788
48    A0049       83729640
49    A0050      113811228

In [67]:
#Q21. Which agents close deals fastest?
# We are checking agent and time taken to sell property

query = """
SELECT l.agent_id, AVG(s.days_on_market) AS avg_days
FROM listings l
JOIN sales s 
ON l.listing_id = s.listing_id
GROUP BY l.agent_id;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID   avg_days
0     A0001  61.934769
1     A0002  45.505647
2     A0003  80.248775
3     A0004  80.087771
4     A0005  63.901358
5     A0006  81.333754
6     A0007  64.473542
7     A0008  46.636009
8     A0009  52.708242
9     A0010  51.131418
10    A0011  64.707348
11    A0012  50.637417
12    A0013  42.428800
13    A0014  67.237257
14    A0015  65.941069
15    A0016  64.537198
16    A0017  48.566175
17    A0018  54.693549
18    A0019  62.002528
19    A0020  62.301740
20    A0021  67.824591
21    A0022  55.555781
22    A0023  56.502256
23    A0024  62.214727
24    A0025  70.768408
25    A0026  49.502797
26    A0027  61.333102
27    A0028  55.599802
28    A0029  62.003297
29    A0030  61.546377
30    A0031  68.619107
31    A0032  62.501184
32    A0033  62.749932
33    A0034  68.290063
34    A0035  67.235123
35    A0036  56.376269
36    A0037  44.500154
37    A0038  70.331742
38    A0039  67.494713
39    A0040  55.923827
40    A0041  56.135224
41    A0042  66.998595
42    A0043  52.351549
43    A0044  36.877523
44    A0045  69.078485
45    A0046  59.896999
46    A0047  61.358609
47    A0048  68.576926
48    A0049  61.802167
49    A0050  62.880843

In [68]:
#Q22:-Does experience affect deals closed?

# We are checking agent experience and deals closed

query = """
SELECT a.experience_years, COUNT(*) AS total_deals
FROM agents a
JOIN listings l ON a.agent_id = l.agent_id
JOIN sales s ON l.listing_id = s.listing_id
GROUP BY a.experience_years
ORDER BY a.experience_years;

"""

df = pd.read_sql(query, conn)
print(df)

    experience_years  total_deals
0                  1          252
1                  2          192
2                  3          192
3                  4          384
4                  5          528
5                  7          264
6                  9          168
7                 10          420
8                 11          204
9                 12          144
10                13          540
11                14          408
12                15          324
13                16          636
14                17          324
15                18          480
16                19          288
17                20          864
18                21          936
19                22          192
20                23          540
21                25          360

In [69]:
#Q23: - Do high-rated agents close faster

# We are checking rating and performance

query = """
SELECT a.rating, AVG(s.days_on_market) AS avg_days
FROM agents a
JOIN listings l ON a.agent_id = l.agent_id
JOIN sales s ON l.listing_id = s.listing_id
GROUP BY a.rating
ORDER BY a.rating DESC;
"""

df = pd.read_sql(query, conn)
print(df)

    rating   avg_days
0      5.0  55.320499
1      4.9  71.102119
2      4.8  58.643937
3      4.6  61.333102
4      4.5  80.087771
5      4.4  52.708242
6      4.3  62.722465
7      4.2  69.078485
8      4.1  58.014676
9      4.0  63.208841
10     3.8  58.853425
11     3.7  62.540614
12     3.6  64.726020
13     3.5  61.497757
14     3.4  57.274573
15     3.3  62.001047
16     3.2  59.818726
17     3.1  63.401808

In [70]:
#Q24: - Average commission by agent

# We are checking commission rates of agents

query = """
SELECT agent_id, AVG(commission_rate) AS avg_commission
FROM agents
GROUP BY agent_id;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID  avg_commission
0     A0001            2.00
1     A0002            2.20
2     A0003            2.85
3     A0004            1.67
4     A0005            1.11
5     A0006            1.58
6     A0007            1.78
7     A0008            1.72
8     A0009            2.85
9     A0010            2.14
10    A0011            2.01
11    A0012            2.37
12    A0013            1.78
13    A0014            1.97
14    A0015            1.49
15    A0016            1.45
16    A0017            2.14
17    A0018            2.63
18    A0019            2.80
19    A0020            2.67
20    A0021            2.73
21    A0022            1.94
22    A0023            1.89
23    A0024            2.95
24    A0025            2.01
25    A0026            1.63
26    A0027            1.92
27    A0028            2.25
28    A0029            2.45
29    A0030            2.79
30    A0031            2.51
31    A0032            2.57
32    A0033            2.56
33    A0034            2.46
34    A0035            2.96
35    A0036            1.73
36    A0037            1.78
37    A0038            1.22
38    A0039            1.37
39    A0040            1.58
40    A0041            1.32
41    A0042            2.24
42    A0043            1.75
43    A0044            1.45
44    A0045            2.50
45    A0046            1.57
46    A0047            1.63
47    A0048            1.34
48    A0049            1.70
49    A0050            2.56

In [71]:
#Q25: - Agents with most active listings

# We are counting how many listings each agent has

query = """
SELECT agent_id, COUNT(*) AS total_listings
FROM listings
GROUP BY agent_id;
"""

df = pd.read_sql(query, conn)
print(df)

   Agent_ID  total_listings
0     A0001            1221
1     A0002            1266
2     A0003            1185
3     A0004            1251
4     A0005            1266
5     A0006            1254
6     A0007            1290
7     A0008            1347
8     A0009            1278
9     A0010            1290
10    A0011            1389
11    A0012            1308
12    A0013            1206
13    A0014            1359
14    A0015            1323
15    A0016            1317
16    A0017            1206
17    A0018            1305
18    A0019            1209
19    A0020            1308
20    A0021            1278
21    A0022            1278
22    A0023            1374
23    A0024            1182
24    A0025            1203
25    A0026            1272
26    A0027            1299
27    A0028            1251
28    A0029            1239
29    A0030            1221
30    A0031            1305
31    A0032            1242
32    A0033            1302
33    A0034            1185
34    A0035            1293
35    A0036            1314
36    A0037            1275
37    A0038            1239
38    A0039            1188
39    A0040            1287
40    A0041            1242
41    A0042            1380
42    A0043            1284
43    A0044            1314
44    A0045            1269
45    A0046            1251
46    A0047            1254
47    A0048            1332
48    A0049            1191
49    A0050            1278

------------------------------------ Buyer & Financing Behavior ------------------------------------------------------

In [72]:
#Q26: - What percentage of buyers are investors vs end users?

# We are checking how many buyers are investors or end users

query = """
SELECT 
    buyer_type,
    COUNT(*) AS total_buyers,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM buyers), 2) AS percentage
FROM buyers
GROUP BY buyer_type;
"""

df = pd.read_sql(query, conn)
print(df)

  buyer_type  total_buyers  percentage
0   End User         20040        50.1
1   Investor         19960        49.9

In [73]:
#Q27:- Which cities have the highest loan uptake rate?

# We are checking loan usage and city (simple view)

query = """
SELECT 
    COUNT(*) AS total_buyers,
    SUM(loan_taken) AS loan_buyers,
    (SUM(loan_taken) * 100.0 / COUNT(*)) AS percentage
FROM buyers;
"""

df = pd.read_sql(query, conn)
print(df)

   total_buyers  loan_buyers  percentage
0         40000        20068       50.17

In [74]:
#Q28: - What is the average loan amount by buyer type?

# We are checking buyer type and loan amount

query = """
SELECT buyer_type, AVG(loan_amount) AS avg_loan
FROM buyers
GROUP BY buyer_type;
"""

df = pd.read_sql(query, conn)
print(df)

  buyer_type      avg_loan
0   End User  2.599434e+06
1   Investor  2.629272e+06

In [75]:
#Q29: - Which payment mode is most commonly used?

# We are checking payment methods used by buyers

query = """
SELECT payment_mode, COUNT(*) AS total
FROM buyers
GROUP BY payment_mode;
"""

df = pd.read_sql(query, conn)
print(df)

    payment_mode  total
0  Bank Transfer   9898
1           Cash  10176
2         Cheque   9902
3            UPI  10024

In [84]:
#Q30 : - Do loan-backed purchases take longer to close?

# We are comparing loan taken with time taken to sell

query = """
SELECT loan_taken, COUNT(*) AS total_buyers
FROM buyers
GROUP BY loan_taken;
"""

df = pd.read_sql(query, conn)
print(df)

   loan_taken  total_buyers
0           0         19932
1           1         20068

In [77]:
import os
print(os.path.abspath("realestate.db"))

c:\Users\HP\Downloads\realestate.db